# Travic-CI-Config file for \Org\Heigl\Hyphenator
#
sudo: false
language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - 7.2
 - nightly

env:
 - DEPS=lowest
 - DEPS=locked
 - DEPS=latest

matrix:
  fast_finish : true
  allow_failures:
      - php: 5.3
      - php: 5.4
      - php: 5.5
      - php: 5.6
      - php: nightly
  exclude:
    - php: 5.3
      env: DEPS=lowest
    - php: 5.3
      env: DEPS=locked
    - php: 5.4
      env: DEPS=lowest
    - php: 5.4
      env: DEPS=locked
    - php: 5.5
      env: DEPS=lowest
    - php: 5.5
      env: DEPS=locked
    - php: 5.6
      env: DEPS=lowest
    - php: 5.6
      env: DEPS=locked
  include:
    - php: 7.2
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
        - CHECK_CS=false

stages:
  - check
  - test

jobs:
  include:
    - stage: check
      php: 7.2
      script:
        - composer cs-check

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require $COMPOSER_ARGS --dev satooshi/php-coveralls ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi
